### ISSUE TITLE
header does not follow BEM specs

### ISSUE THREAD

**Issue by pixelass** [annarolfes/coding-buddies#19]
## Expected
```css
.header--big { /* Block + Modifier(BeM)*/
  height: 81px;
}

.header__title { /* Block + Element(BEm)*/
  margin: 0;
  text-transform: uppercase;
}

.header__label {
  margin: 4px 0;
}
```

## Actual
```css
.header--big { /* Block + Modifier(BeM)*/
  height: 81px;
}

.title__header { /* Block + Element(BEm)*/
  margin: 0;
  text-transform: uppercase;
}

.label__header {
  margin: 4px 0;
}
```

## Resources: 

http://getbem.com/naming/
